# Generated by Django 5.0.2 on 2026-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_created_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('course', 'Course')], default='product', max_length=20),
        ),
    ]
